version: "3.7"
services:
  api_service:
    build: .
    ports:
      - 9094:9094
    depends_on:
      - mysql_db
    networks:
      - metadata

  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: java_to_dev_app_db
      MYSQL_USER: java_to_dev
      MYSQL_PASSWORD: abc
      MYSQL_ROOT_PASSWORD: abc
    networks:
      - metadata


networks:
  metadata:
    driver: bridge


