spring:
  application.name: metadata-class
  profiles.active: local
  datasource:
    url: jdbc:mysql://mysql_db:3306/java_to_dev_app_db
    username: java_to_dev
    password: abc
    initialization-mode: always

springdoc.api-docs:
  path: /swagger-ui

server:
  port: 9094